USE [master]
GO

/****** Object:  Database [EleosHealth]    Script Date: 13/10/2021 18:45:57 ******/
CREATE DATABASE [EleosHealth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EleosHealth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EleosHealth.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EleosHealth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EleosHealth_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EleosHealth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EleosHealth] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EleosHealth] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EleosHealth] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EleosHealth] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EleosHealth] SET ARITHABORT OFF 
GO

ALTER DATABASE [EleosHealth] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EleosHealth] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EleosHealth] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EleosHealth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EleosHealth] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EleosHealth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EleosHealth] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EleosHealth] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EleosHealth] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EleosHealth] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EleosHealth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EleosHealth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EleosHealth] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EleosHealth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EleosHealth] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EleosHealth] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EleosHealth] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EleosHealth] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EleosHealth] SET  MULTI_USER 
GO

ALTER DATABASE [EleosHealth] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EleosHealth] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EleosHealth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EleosHealth] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EleosHealth] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EleosHealth] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EleosHealth] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EleosHealth] SET  READ_WRITE 
GO

